apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-service.fullname" . }}
  labels:
    app: ml-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
        version: {{ .Values.image.tag | default "latest" }}
    spec:
      containers:
        - name: ml-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{ toYaml .Values.resources | nindent 12 }}
